kind: Namespace
apiVersion: v1
metadata:
  name: clusterview
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: clusterview-sa
  namespace: clusterview
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterview-cluster-role
rules:
  - apiGroups:
     - "apps/v1"
     - "v1"
     - ""
    resources:
     - "pods"
     - "nodes"
    verbs:
     - "list"
     - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterview-crb
roleRef:
  name: clusterview-cluster-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: clusterview-sa
  namespace: clusterview
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: clusterview
  namespace: clusterview
spec:
  selector:
    matchLabels:
      app: clusterview
  template:
    metadata:
      labels:
         app: clusterview
    spec:
      serviceAccountName: clusterview-sa
      automountServiceAccountToken: true
      containers:
       - name: clusterview
         image: i2kconnect.azurecr.io/clusterview:0.1.0-SNAPSHOT
         imagePullPolicy: Always
         resources:
           requests:
             memory: 15Mi
             cpu: 50m
         ports:
          - containerPort: 8080
            name: clusterview
---
kind: Service
apiVersion: v1
metadata:
  name: clusterview
  namespace: clusterview
spec:
  type: NodePort
  selector:
    app: clusterview
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: clusterview-port
---
apiVersion: appgw.ingress.azure.io/v1beta1
kind: AzureApplicationGatewayRewrite
metadata:
  name: clusterview-rewrite-rule-set-cr
spec:
  rewriteRules:
  - name: clusterview-prefix
    ruleSequence: 20
    conditions:
    - ignoreCase: false
      negate: false
      variable: var_uri_path
      pattern: /clusterview(.*)
    actions:
      urlConfiguration:
        modifiedPath: var_uri_path_1
        reroute: false
---
kind: Secret
apiVersion: v1
metadata:
  name: cvsecret
  namespace: clusterview
type: kubernetes.io/tls
data:
  tls.crt: <<Paste certificate here>>
  tls.key: <<Paste secret here>>
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/rewrite-rule-set: clusterview-rewrite-rule-set
    appgw.ingress.kubernetes.io/health-probe-path: "/"
  name: clusterview
  namespace: clusterview
spec:
  tls:
   - hosts:
      - <<Paste hostname here>>
     secretName: cvsecret
  rules:
   - host: <<Paste hostname here>>
     http:
      paths:
       - path: /clusterview
         pathType: Prefix
         backend:
           service:
             name: clusterview
             port:
               number: 8080
       